// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT533HJiiTPu5vZAPhSo3lsWhu4dIEc6k',
    appId: '1:353113156628:web:d9610435ce1ceff08e0b01',
    messagingSenderId: '353113156628',
    projectId: 'login-c4575',
    authDomain: 'login-c4575.firebaseapp.com',
    storageBucket: 'login-c4575.appspot.com',
    measurementId: 'G-YH6H0N9LRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg_2MjUEmW5B1BH2RjPOpG2QQBhOjTlGI',
    appId: '1:353113156628:android:91fafc42d385e0fe8e0b01',
    messagingSenderId: '353113156628',
    projectId: 'login-c4575',
    storageBucket: 'login-c4575.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmLospehaBcOurG1DZZJccU9QhH4Zo-C0',
    appId: '1:353113156628:ios:f4eaeaa25bca9d4e8e0b01',
    messagingSenderId: '353113156628',
    projectId: 'login-c4575',
    storageBucket: 'login-c4575.appspot.com',
    iosClientId: '353113156628-5lc4pef5bbam5lptt200nvbn5k59oaus.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmLospehaBcOurG1DZZJccU9QhH4Zo-C0',
    appId: '1:353113156628:ios:f4eaeaa25bca9d4e8e0b01',
    messagingSenderId: '353113156628',
    projectId: 'login-c4575',
    storageBucket: 'login-c4575.appspot.com',
    iosClientId: '353113156628-5lc4pef5bbam5lptt200nvbn5k59oaus.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
